dist: trusty

os:
- linux

language: go

go:
- "1.10"
- tip

matrix:
  allow_failures:
  - go: tip

install:
- go get github.com/mattn/goveralls
- go get github.com/golang/dep/cmd/dep
- dep ensure -vendor-only

script:
- goveralls -service=travis-ci
