[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "~1.8.2"

[[constraint]]
  name = "github.com/h2non/gock"
  version = "~1.0.8"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.1"
