[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "~1.7.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.1"
